# -*- coding: utf-8 -*-
"""IBMDCGNCSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IvsNmfnaoutdfkNlB6Dka6I0OCqEJbDf

**Task 4: Generate Descriptive Statistics and Visualizations**


and

**Task 5: Use the appropriate tests to answer the questions provided**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import scipy.stats
import matplotlib.pyplot as plt

boston_url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ST0151EN-SkillsNetwork/labs/boston_housing.csv'
boston_df=pd.read_csv(boston_url)

"""**Dataset varibales descriptions:**
  

*   CRIM - per capita crime rate by townList item
*   ZN - proportion of residential land zoned for lots over 25,000 sq.ft

* INDUS - proportion of non-retail business acres per town.

*   CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)

*   NOX - nitric oxides concentration (parts per 10 million)

*   RM - average number of rooms per dwelling

*   AGE - proportion of owner-occupied units built prior to 1940

*   DIS - weighted distances to five Boston employment centres

*   RAD - index of accessibility to radial highways

*   TAX - full-value property-tax rate per $10,000

*   PTRATIO - pupil-teacher ratio by town

*  LSTAT - % lower status of the population

*   MEDV - Median value of owner-occupied homes in $1000's
"""

boston_df.head()

"""**Task**: Proivde a boxplot for the Median value of owner-occupied homes"""

ax = sns.boxplot(y="MEDV", data=boston_df)
ax.set_title('Median value of owner-occupied homes')

"""**Task:** Provide a bar plot for the Charles river variable"""

sns.set(style="whitegrid")
ax2 = sns.countplot(x="CHAS", data=boston_df)
ax2.set_title('Number of homes near the Charles River')

"""**Task:** Provide a boxplot for the MEDV variable vs the AGE variable"""

boston_df.loc[(boston_df['AGE'] <= 35), 'Age_group'] = '35 years and younger'
boston_df.loc[(boston_df['AGE'] > 35) & (boston_df['AGE'] < 70), 'Age_group'] = 'between 34 and 70 years'
boston_df.loc[(boston_df['AGE'] >= 70), 'Age_group'] = '70 years and older'

ax3 = sns.boxplot(x='Age_group', y="MEDV",
                 data=boston_df)
ax3.set_title('MEDV variable vs the AGE variable')

ax4 = sns.scatterplot(x='NOX', y= 'INDUS', data=boston_df)
ax4.set_title('Relationship between Nitric oxide concentrations and the proportion of non-retail business acres per town')

"""Based on the scatterplot, there seens to be a positive linear relationship between Nitric oxide concentrations and the proportion of non-retail business acres per town.

**Task**: Create a histogram for the pupil to teacher ratio variable
"""

ax5 = sns.distplot(boston_df['PTRATIO'], kde=False)
ax5.set_title('Pupil to teacher ratio variable')

"""# **Task 5: Use the appropriate tests to answer the questions provided.**

**Question 1**: Is there a significant difference in median value of houses bounded by the Charles river or not? (T-test for independent samples)

Hypothese:

Null Hypothesis: There's no significant difference in median value of houses bounded by the Charles river

Alternative Hypothese: There's a significant difference in median value between houses bounded by the Charles River
"""

boston_df.loc[(boston_df['CHAS'] == 0), 'CHAS_T'] ='AWAY'
boston_df.loc[(boston_df['CHAS'] == 1), 'CHAS_T'] = 'CLOSE'
boston_df.head()

scipy.stats.ttest_ind(boston_df[boston_df['CHAS_T'] == 'AWAY']['MEDV'],
boston_df[boston_df['CHAS_T'] == 'CLOSE']['MEDV'], equal_var = True)

"""The p-value is less than 0.05, we reject the Null Hypothesis, meaning there's a statistical difference between houses close to the Charles River and houses away from the river.

**Question 2**: Is there a difference in Median values of houses (MEDV) for each proportion of owner occupied units built prior to 1940 (AGE)? (ANOVA)

Hypothesis

Null Hypothesis: There's no significant difference in Median value of houses built prior to 1940

Alternative Hypothesis: There's a significant difference in Median value houses built prior to 1940
"""

from statsmodels.formula.api import ols
lm = ols('MEDV ~ AGE', data = boston_df).fit()
table = sm.stats.anova_lm(lm)
print(table)

"""We can conculde, since the p-value is less than 0.05, we reject the Null Hyothesis. Meaning there's a significant difference in Median values of houses built prior to 1940

**Question 3:** Can we conclude that there is no relationship between Nitric oxide concentrations and proportion of non-retail business acres per town? (Pearson Correlation)

**Hypothesis**

Null Hypothesis: There is no correlation between Nitric oxide concentration and
proportion of non-retail business acres per town

Alternative Hypothesis: There is a correlation between Nitric oxide concentration and proportion of non-retail business acres per town
"""

scipy.stats.pearsonr(boston_df['NOX'], boston_df['INDUS'])

"""The Pearson Coefficient is a positive 0.7636 with a p-value less than 0.05, we reject the Null Hypothesis, meaning there is a positive correlation between Nitric oxide and proportion of non-retail buiness acres per town

**Questions 4**:  What is the impact of an additional weighted distance  to the five Boston employment centres on the median value of owner occupied homes? (Regression analysis)

H_0: B1 = 0 (Additional weighted distance to the five Boston employment centers has no effect the median value of owner occupied homes)

H_1: B1 is not equal to 0 (Additional weighted distance to the five Boston employment centers has an effect on the median value of owner occupied homes)
"""

x = boston_df['DIS']
y = boston_df['MEDV']

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x)

model.summary()

"""Conculsion: DIS coef of 1.0916 indicates that an addtional weighted distance to the five Boston employment centers increase the mdeian value of owner occupied homes by 1.0916"""

